version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14.1
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./docker/db:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./docker/php
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        SYMFONY_CLI_VERSION: 4.26.9
    ports:
      - "${PHP_PORT}:9001"
    volumes:
      - .:/var/www/symfony:cached
      - ./docker/logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      args:
        NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
    volumes:
      - ./docker/logs/nginx:/var/log/nginx:cached
      - .:/var/www/symfony:cached
