version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14.1
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/postgresql/data:rw

  php:
    container_name: php
    image: bifidokk/symfony-demo:latest
    ports:
      - "${PHP_PORT}:9001"
    environment:
      APP_ENV: ${APP_ENV}
      MAILER_DSN: ${MAILER_DSN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - app:/var/www/symfony

  nginx:
    container_name: nginx
    image: bifidokk/symfony-demo-nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - app:/var/www/symfony

volumes:
  app: