name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          tags: bifidokk/symfony-demo:latest

      -
        name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          push: true
          tags: bifidokk/symfony-demo-nginx:latest

      -
        name: Restart Docker compose with fresh images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /var/www/symfony-demo
            git pull
            docker compose --file ./docker/docker-compose.yml down
            docker volume rm docker_app
            docker compose --file ./docker/docker-compose.yml pull
            docker compose --file ./docker/docker-compose.yml --env-file ./docker/.env.prod up -d
            docker exec php bin/console cache:clear
            docker exec php bin/console cache:warmup
            docker exec php bin/console doctrine:migrations:migrate --no-interaction