name: Deploy
on: workflow_dispatch
jobs:
  docker:
    env:
      APP_ENV: prod
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          tags: bifidokk/symfony-demo:latest
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          push: true
          tags: bifidokk/symfony-demo-nginx:latest